//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.LangResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.LangResources.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App ähnelt.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps ähnelt.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} gefunden! ähnelt.
        /// </summary>
        internal static string appStatus {
            get {
                return ResourceManager.GetString("appStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Sie sicher? ähnelt.
        /// </summary>
        internal static string AreYouSureMsg {
            get {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung ähnelt.
        /// </summary>
        internal static string columnHeader1 {
            get {
                return ResourceManager.GetString("columnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string columnHeader2 {
            get {
                return ResourceManager.GetString("columnHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string columnHeader3 {
            get {
                return ResourceManager.GetString("columnHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe ähnelt.
        /// </summary>
        internal static string columnHeader4 {
            get {
                return ResourceManager.GetString("columnHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quelle ähnelt.
        /// </summary>
        internal static string columnHeader5 {
            get {
                return ResourceManager.GetString("columnHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank wird abgerufen . . . ähnelt.
        /// </summary>
        internal static string DatabaseAccessMsg {
            get {
                return ResourceManager.GetString("DatabaseAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leider gab es einige Probleme mit den Download-Servern.
        ///Folgende Apps konnten nicht heruntergeladen werden:
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string DownloadErrorMsg {
            get {
                return ResourceManager.GetString("DownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den Vorgang  wiederholen? ähnelt.
        /// </summary>
        internal static string DownloadRetryMsg {
            get {
                return ResourceManager.GetString("DownloadRetryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installierte Hervorheben ähnelt.
        /// </summary>
        internal static string highlightInstalledCheck {
            get {
                return ResourceManager.GetString("highlightInstalledCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Internetverbindung hergestellt werden. ähnelt.
        /// </summary>
        internal static string InternetIsNotAvailableMsg {
            get {
                return ResourceManager.GetString("InternetIsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprachauswahl: ähnelt.
        /// </summary>
        internal static string LangSelectionFormTitel {
            get {
                return ResourceManager.GetString("LangSelectionFormTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S U C H E ähnelt.
        /// </summary>
        internal static string listViewGroup0 {
            get {
                return ResourceManager.GetString("listViewGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barrierefreiheit ähnelt.
        /// </summary>
        internal static string listViewGroup1 {
            get {
                return ResourceManager.GetString("listViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Games ähnelt.
        /// </summary>
        internal static string listViewGroup10 {
            get {
                return ResourceManager.GetString("listViewGroup10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Erweitert ähnelt.
        /// </summary>
        internal static string listViewGroup11 {
            get {
                return ResourceManager.GetString("listViewGroup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Shareware ähnelt.
        /// </summary>
        internal static string listViewGroup12 {
            get {
                return ResourceManager.GetString("listViewGroup12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bildung ähnelt.
        /// </summary>
        internal static string listViewGroup2 {
            get {
                return ResourceManager.GetString("listViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entwicklung ähnelt.
        /// </summary>
        internal static string listViewGroup3 {
            get {
                return ResourceManager.GetString("listViewGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Büro ähnelt.
        /// </summary>
        internal static string listViewGroup4 {
            get {
                return ResourceManager.GetString("listViewGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internet ähnelt.
        /// </summary>
        internal static string listViewGroup5 {
            get {
                return ResourceManager.GetString("listViewGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fotos und Bilder ähnelt.
        /// </summary>
        internal static string listViewGroup6 {
            get {
                return ResourceManager.GetString("listViewGroup6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio und Video ähnelt.
        /// </summary>
        internal static string listViewGroup7 {
            get {
                return ResourceManager.GetString("listViewGroup7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherheit ähnelt.
        /// </summary>
        internal static string listViewGroup8 {
            get {
                return ResourceManager.GetString("listViewGroup8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verschiedenes ähnelt.
        /// </summary>
        internal static string listViewGroup9 {
            get {
                return ResourceManager.GetString("listViewGroup9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauerhaft merken für diese Anwendung ähnelt.
        /// </summary>
        internal static string NoLangQuestionCheck {
            get {
                return ResourceManager.GetString("NoLangQuestionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, es konnte keine Verbindung zum Server aufgebaut werden.
        ///Bitte versuchen Sie es später noch einmal. ähnelt.
        /// </summary>
        internal static string NoServerAvailableMsg {
            get {
                return ResourceManager.GetString("NoServerAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellung für diese Anwendung merken ähnelt.
        /// </summary>
        internal static string rememberLangCheck {
            get {
                return ResourceManager.GetString("rememberLangCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Programm ist unvollständig. Möchten Sie es erneut herunterladen? ähnelt.
        /// </summary>
        internal static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppenfarben Anzeigen ähnelt.
        /// </summary>
        internal static string showColorsCheck {
            get {
                return ResourceManager.GetString("showColorsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppen Anzeigen ähnelt.
        /// </summary>
        internal static string showGroupsCheck {
            get {
                return ResourceManager.GetString("showGroupsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei: {0}/{1} - {2} ähnelt.
        /// </summary>
        internal static string StatusDownload {
            get {
                return ResourceManager.GetString("StatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entpacke Dateien... ähnelt.
        /// </summary>
        internal static string StatusExtract {
            get {
                return ResourceManager.GetString("StatusExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} erfolgreich {1}! ähnelt.
        /// </summary>
        internal static string SuccessfullyDownloadMsg0 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die aktualisiert ähnelt.
        /// </summary>
        internal static string SuccessfullyDownloadMsg1 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die heruntergeladen ähnelt.
        /// </summary>
        internal static string SuccessfullyDownloadMsg2 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} verfügbar. Möchten Sie fortfahren? ähnelt.
        /// </summary>
        internal static string UpdatesAvailableMsg0 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisierungen ähnelt.
        /// </summary>
        internal static string UpdatesAvailableMsg1 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisierung ähnelt.
        /// </summary>
        internal static string UpdatesAvailableMsg2 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg2", resourceCulture);
            }
        }
    }
}
