//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.LangResources.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} gefunden!.
        /// </summary>
        internal static string appStatus {
            get {
                return ResourceManager.GetString("appStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher?.
        /// </summary>
        internal static string AreYouSureMsg {
            get {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishGB,German.
        /// </summary>
        internal static string availableLangs {
            get {
                return ResourceManager.GetString("availableLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung.
        /// </summary>
        internal static string columnHeader1 {
            get {
                return ResourceManager.GetString("columnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string columnHeader2 {
            get {
                return ResourceManager.GetString("columnHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string columnHeader3 {
            get {
                return ResourceManager.GetString("columnHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe.
        /// </summary>
        internal static string columnHeader4 {
            get {
                return ResourceManager.GetString("columnHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle.
        /// </summary>
        internal static string columnHeader5 {
            get {
                return ResourceManager.GetString("columnHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank wird abgerufen . . ..
        /// </summary>
        internal static string DatabaseAccessMsg {
            get {
                return ResourceManager.GetString("DatabaseAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider gab es einige Probleme mit den Download-Servern.
        ///Folgende Apps konnten nicht heruntergeladen werden:
        ///
        ///{0}.
        /// </summary>
        internal static string DownloadErrorMsg {
            get {
                return ResourceManager.GetString("DownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Vorgang  wiederholen?.
        /// </summary>
        internal static string DownloadRetryMsg {
            get {
                return ResourceManager.GetString("DownloadRetryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installierte Hervorheben.
        /// </summary>
        internal static string highlightInstalledCheck {
            get {
                return ResourceManager.GetString("highlightInstalledCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Internetverbindung hergestellt werden..
        /// </summary>
        internal static string InternetIsNotAvailableMsg {
            get {
                return ResourceManager.GetString("InternetIsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Ihrem System konnte keine IPv4-Verbindung aufgebaut werden. Das kann zu unerwünschten Problemen führen.
        ///
        ///Üblicherweise wird bei einem IPv6-Anschluss ein Routing-Verfahren eingesetzt welches die Verbindungen zu Server gewährleistet die nur das IPv4-Protokoll aufweisen. Dieser Dienst ist bei Ihnen nicht verfügbar..
        /// </summary>
        internal static string InternetProtocolWarningMsg {
            get {
                return ResourceManager.GetString("InternetProtocolWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachauswahl:.
        /// </summary>
        internal static string LangSelectionFormTitel {
            get {
                return ResourceManager.GetString("LangSelectionFormTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S U C H E.
        /// </summary>
        internal static string listViewGroup0 {
            get {
                return ResourceManager.GetString("listViewGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrierefreiheit.
        /// </summary>
        internal static string listViewGroup1 {
            get {
                return ResourceManager.GetString("listViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string listViewGroup10 {
            get {
                return ResourceManager.GetString("listViewGroup10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Erweitert.
        /// </summary>
        internal static string listViewGroup11 {
            get {
                return ResourceManager.GetString("listViewGroup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Shareware.
        /// </summary>
        internal static string listViewGroup12 {
            get {
                return ResourceManager.GetString("listViewGroup12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildung.
        /// </summary>
        internal static string listViewGroup2 {
            get {
                return ResourceManager.GetString("listViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwicklung.
        /// </summary>
        internal static string listViewGroup3 {
            get {
                return ResourceManager.GetString("listViewGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büro.
        /// </summary>
        internal static string listViewGroup4 {
            get {
                return ResourceManager.GetString("listViewGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string listViewGroup5 {
            get {
                return ResourceManager.GetString("listViewGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos und Bilder.
        /// </summary>
        internal static string listViewGroup6 {
            get {
                return ResourceManager.GetString("listViewGroup6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio und Video.
        /// </summary>
        internal static string listViewGroup7 {
            get {
                return ResourceManager.GetString("listViewGroup7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheit.
        /// </summary>
        internal static string listViewGroup8 {
            get {
                return ResourceManager.GetString("listViewGroup8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschiedenes.
        /// </summary>
        internal static string listViewGroup9 {
            get {
                return ResourceManager.GetString("listViewGroup9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauerhaft merken für diese Anwendung.
        /// </summary>
        internal static string NoLangQuestionCheck {
            get {
                return ResourceManager.GetString("NoLangQuestionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, es konnte keine Verbindung zum Server aufgebaut werden.
        ///Bitte versuchen Sie es später noch einmal..
        /// </summary>
        internal static string NoServerAvailableMsg {
            get {
                return ResourceManager.GetString("NoServerAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellung für diese Anwendung merken.
        /// </summary>
        internal static string rememberLangCheck {
            get {
                return ResourceManager.GetString("rememberLangCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Programm ist unvollständig. Möchten Sie es erneut herunterladen?.
        /// </summary>
        internal static string RequirementsErrorMsg {
            get {
                return ResourceManager.GetString("RequirementsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppenfarben Anzeigen.
        /// </summary>
        internal static string showColorsCheck {
            get {
                return ResourceManager.GetString("showColorsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen Anzeigen.
        /// </summary>
        internal static string showGroupsCheck {
            get {
                return ResourceManager.GetString("showGroupsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei: {0}/{1} - {2}.
        /// </summary>
        internal static string StatusDownload {
            get {
                return ResourceManager.GetString("StatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entpacke Dateien....
        /// </summary>
        internal static string StatusExtract {
            get {
                return ResourceManager.GetString("StatusExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} erfolgreich {1}!.
        /// </summary>
        internal static string SuccessfullyDownloadMsg0 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktualisiert.
        /// </summary>
        internal static string SuccessfullyDownloadMsg1 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heruntergeladen.
        /// </summary>
        internal static string SuccessfullyDownloadMsg2 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} verfügbar. Möchten Sie fortfahren?.
        /// </summary>
        internal static string UpdatesAvailableMsg0 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierungen.
        /// </summary>
        internal static string UpdatesAvailableMsg1 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierung.
        /// </summary>
        internal static string UpdatesAvailableMsg2 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg2", resourceCulture);
            }
        }
    }
}
