//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.LangResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.LangResources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  {0} {1} found! ähnelt.
        /// </summary>
        internal static string AppStatus {
            get {
                return ResourceManager.GetString("AppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        internal static string AreYouSureMsg {
            get {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        internal static string columnHeader1 {
            get {
                return ResourceManager.GetString("columnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string columnHeader2 {
            get {
                return ResourceManager.GetString("columnHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string columnHeader3 {
            get {
                return ResourceManager.GetString("columnHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        internal static string columnHeader4 {
            get {
                return ResourceManager.GetString("columnHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        internal static string columnHeader5 {
            get {
                return ResourceManager.GetString("columnHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database is being accessed . . . ähnelt.
        /// </summary>
        internal static string DatabaseAccessMsg {
            get {
                return ResourceManager.GetString("DatabaseAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a problem with a server. The following apps could not be downloaded:
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string DownloadErrorMsg {
            get {
                return ResourceManager.GetString("DownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to retry? ähnelt.
        /// </summary>
        internal static string DownloadRetryMsg {
            get {
                return ResourceManager.GetString("DownloadRetryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, no network connection is available. ähnelt.
        /// </summary>
        internal static string InternetIsNotAvailableMsg {
            get {
                return ResourceManager.GetString("InternetIsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S E A R C H ähnelt.
        /// </summary>
        internal static string listViewGroup0 {
            get {
                return ResourceManager.GetString("listViewGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accessibility ähnelt.
        /// </summary>
        internal static string listViewGroup1 {
            get {
                return ResourceManager.GetString("listViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Games ähnelt.
        /// </summary>
        internal static string listViewGroup10 {
            get {
                return ResourceManager.GetString("listViewGroup10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Advanced ähnelt.
        /// </summary>
        internal static string listViewGroup11 {
            get {
                return ResourceManager.GetString("listViewGroup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Shareware ähnelt.
        /// </summary>
        internal static string listViewGroup12 {
            get {
                return ResourceManager.GetString("listViewGroup12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Education ähnelt.
        /// </summary>
        internal static string listViewGroup2 {
            get {
                return ResourceManager.GetString("listViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Development ähnelt.
        /// </summary>
        internal static string listViewGroup3 {
            get {
                return ResourceManager.GetString("listViewGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Office ähnelt.
        /// </summary>
        internal static string listViewGroup4 {
            get {
                return ResourceManager.GetString("listViewGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internet ähnelt.
        /// </summary>
        internal static string listViewGroup5 {
            get {
                return ResourceManager.GetString("listViewGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics and Pictures ähnelt.
        /// </summary>
        internal static string listViewGroup6 {
            get {
                return ResourceManager.GetString("listViewGroup6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music and Video ähnelt.
        /// </summary>
        internal static string listViewGroup7 {
            get {
                return ResourceManager.GetString("listViewGroup7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security ähnelt.
        /// </summary>
        internal static string listViewGroup8 {
            get {
                return ResourceManager.GetString("listViewGroup8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Utilities ähnelt.
        /// </summary>
        internal static string listViewGroup9 {
            get {
                return ResourceManager.GetString("listViewGroup9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, there are currently no download servers available. ähnelt.
        /// </summary>
        internal static string NoServerAvailableMsg {
            get {
                return ResourceManager.GetString("NoServerAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search: ähnelt.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Group Colors ähnelt.
        /// </summary>
        internal static string ShowColorsCheck {
            get {
                return ResourceManager.GetString("ShowColorsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Groups ähnelt.
        /// </summary>
        internal static string ShowGroupsCheck {
            get {
                return ResourceManager.GetString("ShowGroupsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File: {0}/{1} - {2} ähnelt.
        /// </summary>
        internal static string StatusDownload {
            get {
                return ResourceManager.GetString("StatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extracting files... ähnelt.
        /// </summary>
        internal static string StatusExtract {
            get {
                return ResourceManager.GetString("StatusExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} successfully {1}! ähnelt.
        /// </summary>
        internal static string SuccessfullyDownloadMsg0 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die updated ähnelt.
        /// </summary>
        internal static string SuccessfullyDownloadMsg1 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die downloaded ähnelt.
        /// </summary>
        internal static string SuccessfullyDownloadMsg2 {
            get {
                return ResourceManager.GetString("SuccessfullyDownloadMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} available. Would you like to update now? ähnelt.
        /// </summary>
        internal static string UpdatesAvailableMsg0 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die updates are ähnelt.
        /// </summary>
        internal static string UpdatesAvailableMsg1 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die update is ähnelt.
        /// </summary>
        internal static string UpdatesAvailableMsg2 {
            get {
                return ResourceManager.GetString("UpdatesAvailableMsg2", resourceCulture);
            }
        }
    }
}
