//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .free/AppInfo.ini.
        /// </summary>
        internal static string AiPath {
            get {
                return ResourceManager.GetString("AiPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .free/PortableAppsInfo.7z.
        /// </summary>
        internal static string DbPath0 {
            get {
                return ResourceManager.GetString("DbPath0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updater/update.7z.
        /// </summary>
        internal static string DbPath1 {
            get {
                return ResourceManager.GetString("DbPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diagonal_pattern {
            get {
                object obj = ResourceManager.GetObject("diagonal_pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortableAppsSuite/master/AppInfo.ini.
        /// </summary>
        internal static string GitAppInfoPath {
            get {
                return ResourceManager.GetString("GitAppInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ServerInfos/master/DnsInfo.ini.
        /// </summary>
        internal static string GitDnsPath {
            get {
                return ResourceManager.GetString("GitDnsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Si13n7.
        /// </summary>
        internal static string GitProfileUri {
            get {
                return ResourceManager.GetString("GitProfileUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/Si13n7.
        /// </summary>
        internal static string GitRawProfileUri {
            get {
                return ResourceManager.GetString("GitRawProfileUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortableAppsSuite/releases.
        /// </summary>
        internal static string GitReleasesPath {
            get {
                return ResourceManager.GetString("GitReleasesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [default6]
        ///domain=www6.si13n7.com
        ///addr=
        ///ipv6=2a03:4000:0006:80e2:0000:0000:0000:0000
        ///ssl=False.
        /// </summary>
        internal static string IPv6DNS {
            get {
                return ResourceManager.GetString("IPv6DNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.portableapps.com.
        /// </summary>
        internal static string PaDlUrl {
            get {
                return ResourceManager.GetString("PaDlUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads/Portable%20Apps%20Suite.
        /// </summary>
        internal static string PasPath {
            get {
                return ResourceManager.GetString("PasPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portableapps.com.
        /// </summary>
        internal static string PaUrl {
            get {
                return ResourceManager.GetString("PaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.portableapps.com
        ///downloads2.portableapps.com
        ///download3.portableapps.com.
        /// </summary>
        internal static string PaUrls {
            get {
                return ResourceManager.GetString("PaUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PortableApps_purple_64 {
            get {
                object obj = ResourceManager.GetObject("PortableApps_purple_64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PortableAppsBox {
            get {
                object obj = ResourceManager.GetObject("PortableAppsBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %CurDir%\Helper\rvta\RefreshVisibleTrayArea.exe.
        /// </summary>
        internal static string RvtaPath {
            get {
                return ResourceManager.GetString("RvtaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://duckduckgo.com/?q=.
        /// </summary>
        internal static string SearchQueryUri {
            get {
                return ResourceManager.GetString("SearchQueryUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.sourceforge.net.
        /// </summary>
        internal static string SfDlUrl {
            get {
                return ResourceManager.GetString("SfDlUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sourceforge.net.
        /// </summary>
        internal static string SfUrl {
            get {
                return ResourceManager.GetString("SfUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.sourceforge.net
        ///netcologne.dl.sourceforge.net
        ///freefr.dl.sourceforge.net
        ///heanet.dl.sourceforge.net
        ///kent.dl.sourceforge.net
        ///vorboss.dl.sourceforge.net
        ///netix.dl.sourceforge.net.
        /// </summary>
        internal static string SfUrls {
            get {
                return ResourceManager.GetString("SfUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Apps Suite.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
