//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsLauncher.LangResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsLauncher.LangResources.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über Portable Apps Launcher ähnelt.
        /// </summary>
        internal static string AboutFormTitle {
            get {
                return ResourceManager.GetString("AboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portable Apps Suite wird entwickelt und gestaltet von {0},
        ///gegründet und aktiv betrieben von einer Privatperson die mit richtigem Namen 
        ///Roy Schrödel heißt.
        ///
        ///Möchten Sie mich unterstützen? {1} oder {2}!
        ///Bitte fühlen Sie sich ebenso frei Verbesserungsvorschläge zu melden! ähnelt.
        /// </summary>
        internal static string aboutInfoLabel {
            get {
                return ResourceManager.GetString("aboutInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spenden Sie mit PayPal ähnelt.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel1 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die melden Sie ein Problem ähnelt.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel2 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startargumente hinzufügen: ähnelt.
        /// </summary>
        internal static string addArgsLabel {
            get {
                return ResourceManager.GetString("addArgsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu aktuellen Befehlszeilenargumente hinzufügen. ähnelt.
        /// </summary>
        internal static string addArgsLabelTip {
            get {
                return ResourceManager.GetString("addArgsLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Apps hinzufügen. ähnelt.
        /// </summary>
        internal static string addBtnTip {
            get {
                return ResourceManager.GetString("addBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In die Shell aufnehmen ähnelt.
        /// </summary>
        internal static string addToShellBtn {
            get {
                return ResourceManager.GetString("addToShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App-Ordner: ähnelt.
        /// </summary>
        internal static string appDirsLabel {
            get {
                return ResourceManager.GetString("appDirsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Verzeichnisse, die Portable Apps enthalten, hinzufügen:
        ///
        ///- Vollständiges Verzeichnis angeben
        ///- Ein Verzeichnis pro Zeile
        ///- Umgebungsvariablen werden akzeptiert ähnelt.
        /// </summary>
        internal static string appDirsTip {
            get {
                return ResourceManager.GetString("appDirsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausführen ähnelt.
        /// </summary>
        internal static string appMenuItem1 {
            get {
                return ResourceManager.GetString("appMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als Administrator ausführen ähnelt.
        /// </summary>
        internal static string appMenuItem2 {
            get {
                return ResourceManager.GetString("appMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App-Pfad öffnen ähnelt.
        /// </summary>
        internal static string appMenuItem3 {
            get {
                return ResourceManager.GetString("appMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desktopverknüpfung erstellen ähnelt.
        /// </summary>
        internal static string appMenuItem4 {
            get {
                return ResourceManager.GetString("appMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umbenennen ähnelt.
        /// </summary>
        internal static string appMenuItem5 {
            get {
                return ResourceManager.GetString("appMenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie &apos;{0}&apos; wirklich löschen? ähnelt.
        /// </summary>
        internal static string appMenuItem5Msg {
            get {
                return ResourceManager.GetString("appMenuItem5Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string appMenuItem6 {
            get {
                return ResourceManager.GetString("appMenuItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung: ähnelt.
        /// </summary>
        internal static string appsBoxLabel {
            get {
                return ResourceManager.GetString("appsBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} gefunden! ähnelt.
        /// </summary>
        internal static string appsCount {
            get {
                return ResourceManager.GetString("appsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie sollen die Dateitypen zugewiesen werden? ähnelt.
        /// </summary>
        internal static string associateAppWayQuestion {
            get {
                return ResourceManager.GetString("associateAppWayQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateitypen zuordnen ähnelt.
        /// </summary>
        internal static string associateBtn {
            get {
                return ResourceManager.GetString("associateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben noch keine Dateitypen hinzugefügt. ähnelt.
        /// </summary>
        internal static string associateBtnMsg {
            get {
                return ResourceManager.GetString("associateBtnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button-Farbe: ähnelt.
        /// </summary>
        internal static string btnColorPanelLabel {
            get {
                return ResourceManager.GetString("btnColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button-Hover-Farbe: ähnelt.
        /// </summary>
        internal static string btnHoverColorPanelLabel {
            get {
                return ResourceManager.GetString("btnHoverColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button-Text-Farbe: ähnelt.
        /// </summary>
        internal static string btnTextColorPanelLabel {
            get {
                return ResourceManager.GetString("btnTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verlassen ähnelt.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Derzeitige Befehlszeilenargumente. ähnelt.
        /// </summary>
        internal static string clLabelTip {
            get {
                return ResourceManager.GetString("clLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Befehlszeile wurde aktualisiert. ähnelt.
        /// </summary>
        internal static string cmdLineUpdated {
            get {
                return ResourceManager.GetString("cmdLineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control-Farbe: ähnelt.
        /// </summary>
        internal static string controlColorPanelLabel {
            get {
                return ResourceManager.GetString("controlColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control-Text-Farbe: ähnelt.
        /// </summary>
        internal static string controlTextColorPanelLabel {
            get {
                return ResourceManager.GetString("controlTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Ausrichtung: ähnelt.
        /// </summary>
        internal static string defaultPosLabel {
            get {
                return ResourceManager.GetString("defaultPosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startmenü ähnelt.
        /// </summary>
        internal static string defaultPosOption0 {
            get {
                return ResourceManager.GetString("defaultPosOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maus-Cursor ähnelt.
        /// </summary>
        internal static string defaultPosOption1 {
            get {
                return ResourceManager.GetString("defaultPosOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Hintergrund ähnelt.
        /// </summary>
        internal static string defBgCheck {
            get {
                return ResourceManager.GetString("defBgCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinter derzeitigen Befehlszeilenargumenten hinzufügen. ähnelt.
        /// </summary>
        internal static string endArgTip {
            get {
                return ResourceManager.GetString("endArgTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einblenddauer: ähnelt.
        /// </summary>
        internal static string fadeInNumLabel {
            get {
                return ResourceManager.GetString("fadeInNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folgende Dateitypen sind bereits mit anderen Anwendungen verknüpft:
        ///
        ///{0}
        ///
        ///Möchten Sie dennoch fortfahren? ähnelt.
        /// </summary>
        internal static string fileTypesConflictMsg {
            get {
                return ResourceManager.GetString("fileTypesConflictMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateitypen: ähnelt.
        /// </summary>
        internal static string fileTypesLabel {
            get {
                return ResourceManager.GetString("fileTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieren ähnelt.
        /// </summary>
        internal static string fileTypesMenuItem1 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfügen ähnelt.
        /// </summary>
        internal static string fileTypesMenuItem2 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Voreinstellung ähnelt.
        /// </summary>
        internal static string fileTypesMenuItem3 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateitypen können einer Anwendung zugewiesen werden.
        ///
        ///Dateitypen die mit einem Punkt beginnen werden bei
        ///der Dateitypenzuordnung ausgeschlossen.
        ///
        ///Wird einer der eingetragenen Dateitypen mit dem
        ///Protable Apps Launcher geöffnet, wird diese App
        ///automatisch ausgewählt.
        ///Bei deaktivierter Bestätigungsabfrage wird die App,
        ///in folge dessen, ohne Nachfrage gestartet. ähnelt.
        /// </summary>
        internal static string fileTypesTip {
            get {
                return ResourceManager.GetString("fileTypesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hauptfarbe: ähnelt.
        /// </summary>
        internal static string mainColorPanelLabel {
            get {
                return ResourceManager.GetString("mainColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Bestätigungsabfrage für diese App ähnelt.
        /// </summary>
        internal static string noConfirmCheck {
            get {
                return ResourceManager.GetString("noConfirmCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn man diese Option aktiviert, werden
        ///definierte Dateitypen ohne Nachfrage mit
        ///der zugeordneten App gestartet. ähnelt.
        /// </summary>
        internal static string noConfirmCheckTip {
            get {
                return ResourceManager.GetString("noConfirmCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Voreinstellung für diese Anwendung gefunden. ähnelt.
        /// </summary>
        internal static string NoDefaultTypesFoundMsg {
            get {
                return ResourceManager.GetString("NoDefaultTypesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht gefunden... ähnelt.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niemals nach Updates für diese App suchen ähnelt.
        /// </summary>
        internal static string noUpdatesCheck {
            get {
                return ResourceManager.GetString("noUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Updates notwendig! ähnelt.
        /// </summary>
        internal static string NoUpdatesFoundMsg {
            get {
                return ResourceManager.GetString("NoUpdatesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deckkraft: ähnelt.
        /// </summary>
        internal static string opacityNumLabel {
            get {
                return ResourceManager.GetString("opacityNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang wurde abgebrochen. ähnelt.
        /// </summary>
        internal static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang wurde abgeschlossen. ähnelt.
        /// </summary>
        internal static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang ist fehlgeschlagen. ähnelt.
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aus der Shell entfernen ähnelt.
        /// </summary>
        internal static string rmFromShellBtn {
            get {
                return ResourceManager.GetString("rmFromShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese App immer als Administrator ausführen ähnelt.
        /// </summary>
        internal static string runAsAdminCheck {
            get {
                return ResourceManager.GetString("runAsAdminCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string saveBtn {
            get {
                return ResourceManager.GetString("saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich gespeichert. ähnelt.
        /// </summary>
        internal static string SavedSettings {
            get {
                return ResourceManager.GetString("SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S U C H E ähnelt.
        /// </summary>
        internal static string searchBox {
            get {
                return ResourceManager.GetString("searchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrund ändern ähnelt.
        /// </summary>
        internal static string setBgBtn {
            get {
                return ResourceManager.GetString("setBgBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache (Language) ähnelt.
        /// </summary>
        internal static string setLangLabel {
            get {
                return ResourceManager.GetString("setLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string settingsBtn {
            get {
                return ResourceManager.GetString("settingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An &amp;PortableApp weiterleiten ähnelt.
        /// </summary>
        internal static string shellText {
            get {
                return ResourceManager.GetString("shellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung erfolgreich erstellt. ähnelt.
        /// </summary>
        internal static string ShortcutCreatedMsg0 {
            get {
                return ResourceManager.GetString("ShortcutCreatedMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Verknüpfung konnte nicht erstellt werden. ähnelt.
        /// </summary>
        internal static string ShortcutCreatedMsg1 {
            get {
                return ResourceManager.GetString("ShortcutCreatedMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor derzeitigen Befehlszeilenargumenten hinzufügen. ähnelt.
        /// </summary>
        internal static string startArgTip {
            get {
                return ResourceManager.GetString("startArgTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausführen ähnelt.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewähltes Element beim Start: ähnelt.
        /// </summary>
        internal static string startItemLabel {
            get {
                return ResourceManager.GetString("startItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kombinationsfeld ähnelt.
        /// </summary>
        internal static string startItemOption0 {
            get {
                return ResourceManager.GetString("startItemOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchfeld ähnelt.
        /// </summary>
        internal static string startItemOption1 {
            get {
                return ResourceManager.GetString("startItemOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startmenü Integration: ähnelt.
        /// </summary>
        internal static string startMenuIntegrationLabel {
            get {
                return ResourceManager.GetString("startMenuIntegrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deaktiviert ähnelt.
        /// </summary>
        internal static string startMenuIntegrationOption0 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviert ähnelt.
        /// </summary>
        internal static string startMenuIntegrationOption1 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App-Optionen ähnelt.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stil ähnelt.
        /// </summary>
        internal static string tabPage2 {
            get {
                return ResourceManager.GetString("tabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonstiges ähnelt.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateitypenzuordnung rückgängig machen. ähnelt.
        /// </summary>
        internal static string undoAssociationBtnTip {
            get {
                return ResourceManager.GetString("undoAssociationBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach Updates suchen ähnelt.
        /// </summary>
        internal static string updateBtn {
            get {
                return ResourceManager.GetString("updateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update-Suche: ähnelt.
        /// </summary>
        internal static string updateCheckLabel {
            get {
                return ResourceManager.GetString("updateCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niemals ähnelt.
        /// </summary>
        internal static string updateCheckOption0 {
            get {
                return ResourceManager.GetString("updateCheckOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stündlich (Komplett) ähnelt.
        /// </summary>
        internal static string updateCheckOption1 {
            get {
                return ResourceManager.GetString("updateCheckOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stündlich (Nur Apps) ähnelt.
        /// </summary>
        internal static string updateCheckOption2 {
            get {
                return ResourceManager.GetString("updateCheckOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stündlich (Nur Apps Suite) ähnelt.
        /// </summary>
        internal static string updateCheckOption3 {
            get {
                return ResourceManager.GetString("updateCheckOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Täglich (Komplett) ähnelt.
        /// </summary>
        internal static string updateCheckOption4 {
            get {
                return ResourceManager.GetString("updateCheckOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Täglich (Nur Apps) ähnelt.
        /// </summary>
        internal static string updateCheckOption5 {
            get {
                return ResourceManager.GetString("updateCheckOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Täglich (Nur Apps Suite) ähnelt.
        /// </summary>
        internal static string updateCheckOption6 {
            get {
                return ResourceManager.GetString("updateCheckOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monatlich (Komplett) ähnelt.
        /// </summary>
        internal static string updateCheckOption7 {
            get {
                return ResourceManager.GetString("updateCheckOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monatlich (Nur Apps) ähnelt.
        /// </summary>
        internal static string updateCheckOption8 {
            get {
                return ResourceManager.GetString("updateCheckOption8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monatlich (Nur Apps Suite) ähnelt.
        /// </summary>
        internal static string updateCheckOption9 {
            get {
                return ResourceManager.GetString("updateCheckOption9", resourceCulture);
            }
        }
    }
}
