//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsLauncher.LangResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppsLauncher.LangResources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Portable Apps Launcher ähnelt.
        /// </summary>
        internal static string AboutFormTitle {
            get {
                return ResourceManager.GetString("AboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portable Apps Suite is developed and designed by {0},
        ///founded and managed by a single person, his real name is Roy Schroedel.
        ///
        ///Would you like to support me? {1} or {2}!
        ///Please also feel free to report suggestions as well! ähnelt.
        /// </summary>
        internal static string aboutInfoLabel {
            get {
                return ResourceManager.GetString("aboutInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donate by Paypal ähnelt.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel1 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report a Problem ähnelt.
        /// </summary>
        internal static string aboutInfoLabelLinkLabel2 {
            get {
                return ResourceManager.GetString("aboutInfoLabelLinkLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Arguments: ähnelt.
        /// </summary>
        internal static string addArgsLabel {
            get {
                return ResourceManager.GetString("addArgsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add to current command line arguments. ähnelt.
        /// </summary>
        internal static string addArgsLabelTip {
            get {
                return ResourceManager.GetString("addArgsLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download more apps. ähnelt.
        /// </summary>
        internal static string addBtnTip {
            get {
                return ResourceManager.GetString("addBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integrate to Shell ähnelt.
        /// </summary>
        internal static string addToShellBtn {
            get {
                return ResourceManager.GetString("addToShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App Directories: ähnelt.
        /// </summary>
        internal static string appDirsLabel {
            get {
                return ResourceManager.GetString("appDirsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add more directories that contain portable apps:
        ///
        ///- Set full directories
        ///- One directory per line
        ///- Environment variables are accepted ähnelt.
        /// </summary>
        internal static string appDirsTip {
            get {
                return ResourceManager.GetString("appDirsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        internal static string appMenuItem1 {
            get {
                return ResourceManager.GetString("appMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run as administrator ähnelt.
        /// </summary>
        internal static string appMenuItem2 {
            get {
                return ResourceManager.GetString("appMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open app location ähnelt.
        /// </summary>
        internal static string appMenuItem3 {
            get {
                return ResourceManager.GetString("appMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a Desktop Shortcut ähnelt.
        /// </summary>
        internal static string appMenuItem4 {
            get {
                return ResourceManager.GetString("appMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        internal static string appMenuItem5 {
            get {
                return ResourceManager.GetString("appMenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete &apos;{0}&apos;? ähnelt.
        /// </summary>
        internal static string appMenuItem5Msg {
            get {
                return ResourceManager.GetString("appMenuItem5Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string appMenuItem6 {
            get {
                return ResourceManager.GetString("appMenuItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application: ähnelt.
        /// </summary>
        internal static string appsBoxLabel {
            get {
                return ResourceManager.GetString("appsBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} found! ähnelt.
        /// </summary>
        internal static string appsCount {
            get {
                return ResourceManager.GetString("appsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How are the file types to be assigned? ähnelt.
        /// </summary>
        internal static string associateAppWayQuestion {
            get {
                return ResourceManager.GetString("associateAppWayQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Associate File Types ähnelt.
        /// </summary>
        internal static string associateBtn {
            get {
                return ResourceManager.GetString("associateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please add some file types before you use this option. ähnelt.
        /// </summary>
        internal static string associateBtnMsg {
            get {
                return ResourceManager.GetString("associateBtnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button Color: ähnelt.
        /// </summary>
        internal static string btnColorPanelLabel {
            get {
                return ResourceManager.GetString("btnColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button Hover Color: ähnelt.
        /// </summary>
        internal static string btnHoverColorPanelLabel {
            get {
                return ResourceManager.GetString("btnHoverColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button Text Color: ähnelt.
        /// </summary>
        internal static string btnTextColorPanelLabel {
            get {
                return ResourceManager.GetString("btnTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current command line arguments. ähnelt.
        /// </summary>
        internal static string clLabelTip {
            get {
                return ResourceManager.GetString("clLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command Line has been updated. ähnelt.
        /// </summary>
        internal static string cmdLineUpdated {
            get {
                return ResourceManager.GetString("cmdLineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control Color: ähnelt.
        /// </summary>
        internal static string controlColorPanelLabel {
            get {
                return ResourceManager.GetString("controlColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control Text Color: ähnelt.
        /// </summary>
        internal static string controlTextColorPanelLabel {
            get {
                return ResourceManager.GetString("controlTextColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Location ähnelt.
        /// </summary>
        internal static string defaultPosLabel {
            get {
                return ResourceManager.GetString("defaultPosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align to Start Menu ähnelt.
        /// </summary>
        internal static string defaultPosOption0 {
            get {
                return ResourceManager.GetString("defaultPosOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align to Mouse Cursor ähnelt.
        /// </summary>
        internal static string defaultPosOption1 {
            get {
                return ResourceManager.GetString("defaultPosOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Background ähnelt.
        /// </summary>
        internal static string defBgCheck {
            get {
                return ResourceManager.GetString("defBgCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add after the current command line arguments. ähnelt.
        /// </summary>
        internal static string endArgTip {
            get {
                return ResourceManager.GetString("endArgTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fade In Duration: ähnelt.
        /// </summary>
        internal static string fadeInNumLabel {
            get {
                return ResourceManager.GetString("fadeInNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following file type are already defined for a different app:
        ///
        ///{0}
        ///
        ///Do you want to continue? ähnelt.
        /// </summary>
        internal static string fileTypesConflictMsg {
            get {
                return ResourceManager.GetString("fileTypesConflictMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Types: ähnelt.
        /// </summary>
        internal static string fileTypesLabel {
            get {
                return ResourceManager.GetString("fileTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string fileTypesMenuItem1 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string fileTypesMenuItem2 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Default ähnelt.
        /// </summary>
        internal static string fileTypesMenuItem3 {
            get {
                return ResourceManager.GetString("fileTypesMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File types can be assigned to an app. If you open a
        ///file with Portable Apps Launcher this app will auto
        ///selected at startup. ähnelt.
        /// </summary>
        internal static string fileTypesTip {
            get {
                return ResourceManager.GetString("fileTypesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Color: ähnelt.
        /// </summary>
        internal static string mainColorPanelLabel {
            get {
                return ResourceManager.GetString("mainColorPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable confirmation for this app ähnelt.
        /// </summary>
        internal static string noConfirmCheck {
            get {
                return ResourceManager.GetString("noConfirmCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string noConfirmCheckTip {
            get {
                return ResourceManager.GetString("noConfirmCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No default types found for this application. ähnelt.
        /// </summary>
        internal static string NoDefaultTypesFoundMsg {
            get {
                return ResourceManager.GetString("NoDefaultTypesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not found... ähnelt.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Never search updates for this app ähnelt.
        /// </summary>
        internal static string noUpdatesCheck {
            get {
                return ResourceManager.GetString("noUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No updates necessary! ähnelt.
        /// </summary>
        internal static string NoUpdatesFoundMsg {
            get {
                return ResourceManager.GetString("NoUpdatesFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opacity: ähnelt.
        /// </summary>
        internal static string opacityNumLabel {
            get {
                return ResourceManager.GetString("opacityNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation canceled. ähnelt.
        /// </summary>
        internal static string OperationCanceledMsg {
            get {
                return ResourceManager.GetString("OperationCanceledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation completed. ähnelt.
        /// </summary>
        internal static string OperationCompletedMsg {
            get {
                return ResourceManager.GetString("OperationCompletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation failed. ähnelt.
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove from Shell ähnelt.
        /// </summary>
        internal static string rmFromShellBtn {
            get {
                return ResourceManager.GetString("rmFromShellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run this app always with administrator privileges ähnelt.
        /// </summary>
        internal static string runAsAdminCheck {
            get {
                return ResourceManager.GetString("runAsAdminCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string saveBtn {
            get {
                return ResourceManager.GetString("saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings successfully saved. ähnelt.
        /// </summary>
        internal static string SavedSettings {
            get {
                return ResourceManager.GetString("SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S E A R C H ähnelt.
        /// </summary>
        internal static string searchBox {
            get {
                return ResourceManager.GetString("searchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Background ähnelt.
        /// </summary>
        internal static string setBgBtn {
            get {
                return ResourceManager.GetString("setBgBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string setLangLabel {
            get {
                return ResourceManager.GetString("setLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string settingsBtn {
            get {
                return ResourceManager.GetString("settingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open with &amp;PortableApp ähnelt.
        /// </summary>
        internal static string shellText {
            get {
                return ResourceManager.GetString("shellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcut successfully created. ähnelt.
        /// </summary>
        internal static string ShortcutCreatedMsg0 {
            get {
                return ResourceManager.GetString("ShortcutCreatedMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcut could not be created. ähnelt.
        /// </summary>
        internal static string ShortcutCreatedMsg1 {
            get {
                return ResourceManager.GetString("ShortcutCreatedMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add before the current command line arguments. ähnelt.
        /// </summary>
        internal static string startArgTip {
            get {
                return ResourceManager.GetString("startArgTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewähltes Element beim Start: ähnelt.
        /// </summary>
        internal static string startItemLabel {
            get {
                return ResourceManager.GetString("startItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Combobox ähnelt.
        /// </summary>
        internal static string startItemOption0 {
            get {
                return ResourceManager.GetString("startItemOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searchbox ähnelt.
        /// </summary>
        internal static string startItemOption1 {
            get {
                return ResourceManager.GetString("startItemOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Menu integration: ähnelt.
        /// </summary>
        internal static string startMenuIntegrationLabel {
            get {
                return ResourceManager.GetString("startMenuIntegrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        internal static string startMenuIntegrationOption0 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        internal static string startMenuIntegrationOption1 {
            get {
                return ResourceManager.GetString("startMenuIntegrationOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App Options ähnelt.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style ähnelt.
        /// </summary>
        internal static string tabPage2 {
            get {
                return ResourceManager.GetString("tabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo file type association. ähnelt.
        /// </summary>
        internal static string undoAssociationBtnTip {
            get {
                return ResourceManager.GetString("undoAssociationBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        internal static string updateBtn {
            get {
                return ResourceManager.GetString("updateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search for Updates: ähnelt.
        /// </summary>
        internal static string updateCheckLabel {
            get {
                return ResourceManager.GetString("updateCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Never ähnelt.
        /// </summary>
        internal static string updateCheckOption0 {
            get {
                return ResourceManager.GetString("updateCheckOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hourly (full) ähnelt.
        /// </summary>
        internal static string updateCheckOption1 {
            get {
                return ResourceManager.GetString("updateCheckOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hourly (only apps) ähnelt.
        /// </summary>
        internal static string updateCheckOption2 {
            get {
                return ResourceManager.GetString("updateCheckOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hourly (only apps suite) ähnelt.
        /// </summary>
        internal static string updateCheckOption3 {
            get {
                return ResourceManager.GetString("updateCheckOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily (full) ähnelt.
        /// </summary>
        internal static string updateCheckOption4 {
            get {
                return ResourceManager.GetString("updateCheckOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily (only apps) ähnelt.
        /// </summary>
        internal static string updateCheckOption5 {
            get {
                return ResourceManager.GetString("updateCheckOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily (only apps suite) ähnelt.
        /// </summary>
        internal static string updateCheckOption6 {
            get {
                return ResourceManager.GetString("updateCheckOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly (full) ähnelt.
        /// </summary>
        internal static string updateCheckOption7 {
            get {
                return ResourceManager.GetString("updateCheckOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly (only apps) ähnelt.
        /// </summary>
        internal static string updateCheckOption8 {
            get {
                return ResourceManager.GetString("updateCheckOption8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly (only apps suite) ähnelt.
        /// </summary>
        internal static string updateCheckOption9 {
            get {
                return ResourceManager.GetString("updateCheckOption9", resourceCulture);
            }
        }
    }
}
